apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  creationTimestamp: '2022-09-29T14:13:41Z'
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/csi-vsphere-vmware-com
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2022-09-29T14:13:41Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
          f:finalizers:
            v:"external-attacher/csi-vsphere-vmware-com": {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
              f:type: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: Go-http-client
      operation: Update
      time: '2022-09-29T14:13:42Z'
  name: pvc-85f658e2-3fd5-48fa-9501-70b285af3a88
  resourceVersion: '61705841'
  uid: 24e822dc-de67-472a-a5b8-24432ee025f0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datalogdir-ms-cp-zookeeper-2
    namespace: nam-kafka
    resourceVersion: '61705804'
    uid: 85f658e2-3fd5-48fa-9501-70b285af3a88
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1663683358191-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: 5d7ccfad-1c7e-46c4-8e7b-bdc46cc0b760
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vsphere-csi-sc
  volumeMode: Filesystem
status:
  phase: Bound
