apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  creationTimestamp: '2022-09-29T14:09:41Z'
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/csi-vsphere-vmware-com
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2022-09-29T14:09:41Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
          f:finalizers:
            v:"external-attacher/csi-vsphere-vmware-com": {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
              f:type: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: Go-http-client
      operation: Update
      time: '2022-09-29T14:09:42Z'
  name: pvc-47eea44c-88a4-44fd-bde3-74057ab146b4
  resourceVersion: '61704231'
  uid: 095bdf0e-3ca1-4bf3-9823-a5035dd3b46b
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-ms-cp-zookeeper-1
    namespace: nam-kafka
    resourceVersion: '61704188'
    uid: 47eea44c-88a4-44fd-bde3-74057ab146b4
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1663683358191-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: cbf2e198-faed-4ad7-bcb2-4df829b10aab
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vsphere-csi-sc
  volumeMode: Filesystem
status:
  phase: Bound
