apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  creationTimestamp: '2023-11-30T09:44:27Z'
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/csi-vsphere-vmware-com
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-name: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-namespace: {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
              f:type: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: csi-provisioner
      operation: Update
      time: '2023-11-30T09:44:27Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2023-11-30T09:44:27Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"external-attacher/csi-vsphere-vmware-com": {}
      manager: csi-attacher
      operation: Update
      time: '2023-11-30T09:44:28Z'
  name: pvc-48ffdc2f-97bf-49cc-b64c-d6c2dbdf114e
  resourceVersion: '287768275'
  uid: 2488d487-17b1-451c-92a5-19a679021f79
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datalogdir-ms-cp-zookeeper-0
    namespace: nam-kafka
    resourceVersion: '287768230'
    uid: 48ffdc2f-97bf-49cc-b64c-d6c2dbdf114e
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1701331157200-8081-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: 34a65a69-dbbc-4ce2-9341-f78193f15fac
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vsphere-csi-sc
  volumeMode: Filesystem
status:
  phase: Bound
