apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: ms-cp
    meta.helm.sh/release-namespace: nam-kafka
  creationTimestamp: '2022-07-25T16:26:39Z'
  labels:
    app.kubernetes.io/instance: ms-cp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 6.2.0
    helm.sh/chart: zookeeper-6.2.0
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
      manager: helm
      operation: Update
      time: '2022-07-25T16:26:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:secrets:
          .: {}
          k:{"name":"ms-cp-zookeeper-serviceaccount-token-wk2pl"}: {}
      manager: kube-controller-manager
      operation: Update
      time: '2023-01-11T08:09:47Z'
  name: ms-cp-zookeeper-serviceaccount
  namespace: nam-kafka
  resourceVersion: '120660064'
  uid: 3160d531-9525-4bad-8c76-ce52f620aa5a
secrets:
  - name: ms-cp-zookeeper-serviceaccount-token-wk2pl
