apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ms-cp
    meta.helm.sh/release-namespace: nam-kafka
  creationTimestamp: '2022-09-30T13:07:50Z'
  labels:
    app.kubernetes.io/instance: ms-cp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/version: 6.2.0
    helm.sh/chart: zookeeper-6.2.0
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":2181,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: helm
      operation: Update
      time: '2022-09-30T13:07:50Z'
  name: ms-cp-zookeeper
  namespace: nam-kafka
  resourceVersion: '62163576'
  uid: 898c456b-3f02-434f-9ff8-1fdc9d4beccd
spec:
  clusterIP: 10.43.27.39
  clusterIPs:
    - 10.43.27.39
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app.kubernetes.io/instance: ms-cp
    app.kubernetes.io/name: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
